server:
  port: 5001
  forward-headers-strategy: framework
 
spring:
  datasource:
    password: bcb@1234
    driver-class-name: org.postgresql.Driver
    username: postgres
    url: jdbc:postgresql://localhost:5432/user-db
  jpa:
    open-in-view: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        ddl-auto: update
    hibernate:
       naming-strategy: org.hibernate.cfg.ImprovedNamingStrategy
       naming:
         physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    show-sql: true
  servlet:
    multipart:
      max-file-size: 2MB
      max-request-size: 2MB
  mail:
    host: smtp.gmail.com
    port: 587
    username: bathulabrahmaiah@gmail.com
    password: 9010855615
    properties:
      mail:
        smtp:
        auth: true
        starttls:
          enable: true